services:
  koshelf-sync:
    container_name: koshelf-sync
    build:
      context: .
      dockerfile: Dockerfile
    image: koshelf/koshelf-sync:latest
    ports:
      - 7200:7200
      - 17200:17200
    restart: unless-stopped
    volumes:
      - ./logs/app:/app/koshelf-sync/logs
      - ./logs/redis:/var/log/redis
      - ./data/redis:/var/lib/redis
    env_file:
      - ./audiobookshelf.env
